# Generated by Django 5.1.4 on 2025-02-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('N5', 'N5 - Beginner'), ('N4', 'N4 - Upper Beginner'), ('N3', 'N3 - Intermediate'), ('N2', 'N2 - Upper Intermediate'), ('N1', 'N1 - Advanced')], default='N5', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LessonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_details', to='japan.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('kanji', 'Kanji'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading')], max_length=20)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='japan.lessondetail')),
            ],
        ),
    ]
