# Generated by Django 5.1.4 on 2025-02-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('kanji', 'Kanji'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('other', 'Other')], max_length=20),
        ),
    ]
