# Generated by Django 5.1.4 on 2025-02-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0006_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessondetail',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lessondetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessondetail',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
