# Generated by Django 5.1.4 on 2025-02-20 10:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0008_userprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japan.lesson'),
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='quiz_score',
        ),
    ]
