# Generated by Django 5.1.4 on 2025-02-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0010_progress_delete_userprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='listening/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
