# Generated by Django 5.1.4 on 2025-02-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0013_post2_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qzText', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=50)),
                ('quiz_type', models.CharField(choices=[('Vocabulary', 'Vocabulary'), ('Grammer', 'Grammar'), ('Kanji', 'Kanji')], max_length=20)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansText', models.CharField(max_length=2000)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='japan.questiondetail')),
            ],
        ),
        migrations.AddField(
            model_name='questiondetail',
            name='qzQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='japan.quizmodel'),
        ),
    ]
