# Generated by Django 5.1.4 on 2025-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0015_quizscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
    ]
