# Generated by Django 5.1.4 on 2025-02-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0016_quizscore_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizscore',
            old_name='total_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='quizscore',
            name='attempts',
        ),
    ]
