# Generated by Django 5.1.4 on 2025-02-26 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0017_rename_total_score_quizscore_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondetail',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='japan.quizmodel'),
        ),
    ]
