# Generated by Django 5.1.4 on 2025-03-03 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0018_questiondetail_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondetail',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='questiondetail',
            name='qzQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='japan.quizmodel'),
        ),
    ]
