# Generated by Django 5.1.4 on 2025-03-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0019_remove_questiondetail_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='quiz_type',
            field=models.CharField(choices=[('Vocabulary', 'Vocabulary'), ('Grammar', 'Grammar'), ('Kanji', 'Kanji')], max_length=20),
        ),
    ]
