# Generated by Django 5.1.4 on 2025-03-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0020_alter_quizmodel_quiz_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listening',
            name='description',
        ),
    ]
