# Generated by Django 5.1.4 on 2025-05-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0021_remove_listening_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessondetail',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listening',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post2',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referencebook',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
