# Generated by Django 5.1.4 on 2025-08-21 13:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0022_lessondetail_archived_listening_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_videos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
