# Generated by Django 5.1.4 on 2025-08-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0023_progress_completed_at_progress_completed_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='completed_videos',
        ),
    ]
