# Generated by Django 5.1.4 on 2025-08-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0027_remove_progress_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='japan.video'),
        ),
    ]
