# Generated by Django 5.1.4 on 2025-08-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0028_progress_completed_at_progress_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoProgress',
        ),
    ]
