# Generated by Django 5.1.4 on 2025-08-22 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0031_alter_progress_video'),  # make sure this exists
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='video',
            field=models.ForeignKey(
                to='japan.Video',
                on_delete=django.db.models.deletion.CASCADE,
                null=True,   # allow NULLs
                blank=True,  # optional in forms/admin
            ),
        ),
    ]
