# Generated by Django 5.1.4 on 2025-08-22 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0032_alter_progress_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='japan.video'),
        ),
    ]
