# Generated by Django 5.1.4 on 2025-08-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0033_alter_progress_video'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set(),
        ),
    ]
