# Generated by Django 5.1.4 on 2025-08-22 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0034_alter_progress_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(condition=models.Q(('video__isnull', False)), fields=('user', 'video'), name='unique_user_video'),
        ),
    ]
