# Generated by Django 5.1.4 on 2025-08-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0035_progress_unique_user_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('front_image', models.ImageField(upload_to='front_images/')),
                ('back_image', models.ImageField(upload_to='back_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
