# Generated by Django 5.1.4 on 2025-08-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0036_imagecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecard',
            name='level',
            field=models.CharField(choices=[('N5', 'JLPT N5'), ('N4', 'JLPT N4'), ('N3', 'JLPT N3'), ('N2', 'JLPT N2'), ('N1', 'JLPT N1')], default='N5', max_length=10),
        ),
        migrations.AlterField(
            model_name='imagecard',
            name='back_image',
            field=models.ImageField(upload_to='flashcards/back/'),
        ),
        migrations.AlterField(
            model_name='imagecard',
            name='front_image',
            field=models.ImageField(upload_to='flashcards/front/'),
        ),
        migrations.AlterField(
            model_name='imagecard',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
