# Generated by Django 5.1.4 on 2025-08-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0038_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='quiz_type',
            field=models.CharField(choices=[('Vocabulary', 'Vocabulary'), ('Grammar', 'Grammar'), ('Kanji', 'Kanji'), ('All', 'All')], max_length=20),
        ),
    ]
