# Generated by Django 5.1.4 on 2025-08-30 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan', '0040_achievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listening',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listening',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ListeningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('listening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='japan.listening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Listening Progress',
                'unique_together': {('user', 'listening')},
            },
        ),
    ]
